
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.rex.compiladormultilenguajeservidor.utilidades.proyecto.analisis;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int ET_PAQUETE_ARCHIVO_FIN = 25;
  public static final int ET_NOMBRE_PAQUETE_INIC = 10;
  public static final int ET_ID_PAQUETE_INIC = 12;
  public static final int ET_NOMBRE_PAQUETE_FIN = 11;
  public static final int ET_PAQUETE_PRINCIPAL_FIN = 7;
  public static final int ET_PAQUETE_INIC = 8;
  public static final int ET_CODIGO_ARCHIVO_INIC = 26;
  public static final int ET_NOMBRE_ARCHIVO_FIN = 21;
  public static final int CODIGO = 28;
  public static final int ET_NOMBRE_ARCHIVO_INIC = 20;
  public static final int ET_PAQUETE_FIN = 9;
  public static final int ET_ARCHIVOS_PAQUETE_INIC = 16;
  public static final int ID_NOMBRE = 29;
  public static final int ET_PAQUETE_ARCHIVO_INIC = 24;
  public static final int ET_NOMBRE_PROYECTO_FIN = 5;
  public static final int ET_PAQUETE_PRINCIPAL_INIC = 6;
  public static final int ET_ARCHIVO_FIN = 19;
  public static final int ET_ID_ARCHIVO_FIN = 23;
  public static final int EOF = 0;
  public static final int ET_PROYECTO_INIC = 2;
  public static final int ET_ARCHIVOS_PAQUETE_FIN = 17;
  public static final int ET_PROYECTO_FIN = 3;
  public static final int ET_CODIGO_ARCHIVO_FIN = 27;
  public static final int ET_PAQUETES_PAQUETE_INIC = 14;
  public static final int error = 1;
  public static final int ET_PAQUETES_PAQUETE_FIN = 15;
  public static final int ET_ID_ARCHIVO_INIC = 22;
  public static final int ET_ID_PAQUETE_FIN = 13;
  public static final int ET_ARCHIVO_INIC = 18;
  public static final int ET_NOMBRE_PROYECTO_INIC = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ET_PROYECTO_INIC",
  "ET_PROYECTO_FIN",
  "ET_NOMBRE_PROYECTO_INIC",
  "ET_NOMBRE_PROYECTO_FIN",
  "ET_PAQUETE_PRINCIPAL_INIC",
  "ET_PAQUETE_PRINCIPAL_FIN",
  "ET_PAQUETE_INIC",
  "ET_PAQUETE_FIN",
  "ET_NOMBRE_PAQUETE_INIC",
  "ET_NOMBRE_PAQUETE_FIN",
  "ET_ID_PAQUETE_INIC",
  "ET_ID_PAQUETE_FIN",
  "ET_PAQUETES_PAQUETE_INIC",
  "ET_PAQUETES_PAQUETE_FIN",
  "ET_ARCHIVOS_PAQUETE_INIC",
  "ET_ARCHIVOS_PAQUETE_FIN",
  "ET_ARCHIVO_INIC",
  "ET_ARCHIVO_FIN",
  "ET_NOMBRE_ARCHIVO_INIC",
  "ET_NOMBRE_ARCHIVO_FIN",
  "ET_ID_ARCHIVO_INIC",
  "ET_ID_ARCHIVO_FIN",
  "ET_PAQUETE_ARCHIVO_INIC",
  "ET_PAQUETE_ARCHIVO_FIN",
  "ET_CODIGO_ARCHIVO_INIC",
  "ET_CODIGO_ARCHIVO_FIN",
  "CODIGO",
  "ID_NOMBRE"
  };
}

